name: Greetings
on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
    - uses: actions/first-interaction@v1
    # At this moment, this GitHub Action has an issue: https://github.com/actions/first-interaction/issues/101
    # In order to try to solve this, we use this: https://github.com/keploy/keploy/pull/182/files 
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening this issue 😊 ! We really appreciate your work. Happy Coding 🎉🎊 !'' first issue'
        pr-message: 'Thanks for opening this pull request 😊 ! We really appreciate your work. Happy Coding 🎉🎊 !'' first pull request'
